### PR TITLE
Search for text in a table and operate the specific column of the found row

### PR DESCRIPTION
**Pull request by harokki**
This is the applied version of [Find an element by its innerText](https://javascript-snippets.autify.com/snippets/others/find_by_innertext/).
We have received several inquiries that use this JS snippet, so I created this snippet.

### CODE REVIEW

**Comment by sfjt** [comment]
@harokki 
The idea itself looks very good.
But I think using XPath might be a better solution.
(It was me who created the "Find by innerText" snippet, however, I found there have already been an XPath snippet that can be used for the same purpose lol 😂 )
Let me create a change request soon.

**Review by sfjt — APPROVED** [review]
I've 
- updated the code using XPath
- put `element.parentNode` in a loop (just in case)
Could you please double check the code to make sure it works with the use case in your mind.
Maybe we want to another review from someone else though...

**Comment by harokki** [comment]
@sfjt 
Thanks for the fix!
I think this is a more reliable code and lgtm.

@meih 
Could you please check when you have time? 🙏

**Comment by meih** [comment]
Looks good, thank you both! (Cannot approve from the iPhone app 😂)

**Pull request merged**
