### PR TITLE
Snippets to emulate a drag-and-drop operation

### PR DESCRIPTION
**Pull request by FujiHaruka**
I added snippets to emulate a drag-and-drop operation.

There are some variations of implementation for a drag-and-drop feature, so I added 2 snippets: one is based on drag events and the other is based on mouse events.

I don't mean that they covers all cases, but I believe they cover typical cases.

Besides, I gave up IE supports in them because:
- it doesn't support `DragEvent`
- (I guess) it doesn't support setting `clientX` in `MouseEvent`

### CODE REVIEW

**Review by tsuemura — APPROVED** [review]

**Review by rieko-araki — APPROVED** [review]
I don’t know why you send me this review request, but I approve it anyway...

**Comment by meih** [comment]
@FujiHaruka 
Thanks for your great work!

>  I gave up IE supports in them
Can you state that in the comments in the snippets?  Thanks!

**Review by macoril — CHANGES_REQUESTED** [review]
Thanks for the great snippets! and sorry for my late review.
But it is not easy to understand for users who are not good at coding.
To clarify what they need to set what kind of values for each value, please add an explanation about variables.

このままだとあまり詳しくないユーザーがみても各変数にどういったものをいれればいいかわからないので、説明を追加してほしいです。

ref: https://github.com/autifyhq/autify-javascript-snippets/blob/master/snippets/assert-disabled.js

**Comment by macoril** [comment]
Adding notes that these snippets don't work on IE is also a nice idea.
It's a piece of valuable information for users.
Without telling this info, they will make some tries on IE and send inquiries "this snippet doesn't work".

**Comment by meih** [comment]
@FujiHaruka 
Thanks a lot!  Since it looks like all the suggestions are reflected, let me merge this one

**Comment by FujiHaruka** [comment]
@meih Thank you! I've forgotten let you know I modified, but you noticed it!

**Pull request merged**
