### PR TITLE
updated find_by_innertext example (now it uses XPath)

### PR DESCRIPTION
**Pull request by sfjt**
Updated an existing snippet.
From CSS Selector to XPath.
I believe it becomes more intuitive this way.

### CODE REVIEW

**Review by nasum — CHANGES_REQUESTED** [review]
@sfjt I'm not quite sure if this is intuitive or not, but I don't think it is enough to erase the method of specifying by CSS selectors.
Why not add it without updating it?

**Comment by sfjt** [comment]
Hi @nasum 
OK, I'll add the XPath version and keep the CSS Selector version as well.
Let me update the PR.

**Comment by sfjt** [comment]
@nasum Updated.
Could you review the code again?

**Review by nasum — APPROVED** [review]
LGTM

**Pull request merged**
